version: '3.4'

services:
  authenticationtest:
    image: ${DOCKER_REGISTRY-}authenticationtest
    build:
      context: .
      dockerfile: AuthenticationTest/Dockerfile
  projectsetup.db:
    image: postgres:latest
    container_name: Database
    environment:
      - POSTGRES_DB=projectsetup-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
